apiVersion: v1
kind: Namespace
metadata:
  name: linkerd
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
spec:
  commonName: identity.linkerd.cluster.local
  duration: 72h
  renewBefore: 4h
  isCA: true
  usages:
  - cert sign
  - crl sign
  - server auth
  - client auth
  issuerRef:
    name: linkerd-trust-anchor
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA  
  secretName: linkerd-identity-issuer
